# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-01 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Three',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=200)),
                ('travel_from', models.DateField()),
                ('travel_to', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fkonetom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='login.User')),
            ],
        ),
    ]
